config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :courses
  resources :users, only: [:index]
  get 'home/index'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates :title,  presence: true
  validates :description, presence: true, length: { :minimum => 5 }

  belongs_to :user

  def to_s
    title
  end
  has_rich_text :description

  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :confirmable
  def to_s
    email
  end

  has_many :courses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = if params[:title]
      Course.where('title ILIKE ?', "%#{params[:title]}%") #case-insensitive
    else
      Course.all
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)
    @course.user = current_user

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_course
    @course = Course.friendly.find(params[:id])
  end

    # Only allow a list of trusted parameters through.
  def course_params
    params.require(:course).permit(:title, :description)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index]
  def index
    @courses = Course.all.limit(3)
    @latest_couses = Course.all.limit(3).order(created_at: :desc)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(created_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/courses/_course.html.erb
<div class="card">
  <div class="card-header">
    <div class="fa fa-book"></div>
    <%= link_to course.title, course_path(course) %>
  </div>
  <div class="card-body">
    <%= course.description %>
  </div>
  <div class="card-footer">
    <div class="far fa-clock"></div>
    <%= course.created_at.strftime('%d-%b-%Y') %>
    <div class="row"></div>
    <div class="fa fa-chalkboard-teacher"></div>
    <%= course.user %>
  </div>
  <div class="card-footer">
    <%= link_to 'View', course, class: 'btn btn-sm btn-primary text-white' %>
    <%= link_to 'Edit', edit_course_path(course), class: 'btn btn-sm btn-info text-white' %>
    <%= link_to 'Delete', course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger text-white' %>
  </div>
</div>

app/views/courses/_form.html.erb
<%= simple_form_for(@course) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.label :description %>
    <%= f.rich_text_area :description %>
  </div>

  <div class="form-actions mt-3">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<div class="card">
  <div class="card-header">
    <h1>Editing course</h1>
  </div>
  <div class="card-body">
    <%= render 'form' %>
  </div>
</div>
<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>
  Courses:
  <%= @courses.count %>
</h1>
<div class="card-columns">
  <% @courses.each do |course| %>
    <%= render 'courses/course', course: course %>
  <% end %>
</div>
<br/>

app/views/courses/new.html.erb
<div class="card">
  <div class="card-header">
    <h1>New course</h1>
  </div>
  <div class="card-body">
    <%= render 'form' %>
  </div>
</div>
<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<%= link_to 'Courses', courses_path %>
/
<%= link_to @course.title, course_path(@course) %>
<p></p>
<%= render 'courses/course', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/home/index.html.erb
<div class="jumbotron">
  <div class="display-4">
    What do you want to learn today?
  </div>
  <div class="p-4"></div>
  <div class="form-inline my-2 my-lg-0">
    <%= form_tag(courses_path, method: :get) do %>
      <div class="input-group">
        <%= text_field_tag :title, params[:title], autocomplete: 'off', placeholder: "Search", class: 'form-control-sm' %>
        <span class="input-group-append">
          <button class="btn btn-primary btn-sm" type="submit">
            <span aria-hidden="true" class="fa fa-search"></span>
          </button>
        </span>
      </div>
    <% end %>
  </div>
</div>
<div class="card-group">
  <div class="card card-body">
    <h1>
      <div class="fa fa-graduation-cap"></div>
    </h1>
    <%= Course.count %>
    online courses
    <div class="row"></div>
    Explore a variety of fresh topics
  </div>
  <div class="card card-body">
    <h1>
      <div class="fa fa-chalkboard-teacher"></div>
      <!--.fa.fa-brain
      -->
    </h1>
    <%= Course.distinct.count(:user_id) %>
    expert instructors
    <div class="row"></div>
    Find the right instructor for you
  </div>
  <div class="card card-body">
    <h1>
      <div class="fa fa-user-graduate"></div>
    </h1>
    <%= User.count %>
    active learners
    <div class="row"></div>
    Join the knowledge sharing community
  </div>
  <div class="card card-body">
    <h1>
      <div class="fa fa-infinity"></div>
    </h1>
    Lifetime access
    <div class="row"></div>
    Learn on your schedule
  </div>
</div>
<hr/>
<h2>
  Popular courses
</h2>
<div class="card-columns">
  <% @courses.each do |course| %>
    <%= render 'courses/course', course: course %>
  <% end %>
</div>
<hr/>
<h2>
  Top rated courses
</h2>
<div class="card-columns">
  <% @courses.each do |course| %>
    <%= render 'courses/course', course: course %>
  <% end %>
</div>
<hr/>
<h2>
  Latest courses
</h2>
<div class="card-columns">
  <% @latest_couses.each do |course| %>
    <%= render 'courses/course', course: course %>
  <% end %>
</div>
<hr/>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Tech Upskill</a>
  <button aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#navbarSupportedContent" data-toggle="collapse" type="button">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <% if current_user %>
      <ul class="navbar-nav mr-auto">
        <li class="<%= 'active font-weight-bold' if current_page?(root_path) %> nav-item">
          <%= link_to root_path, class: 'nav-link' do %>
            <div class="fa fa-home"></div>
            Home
          <% end %>
        </li>
        <li class="<%= 'active font-weight-bold' if current_page?(courses_path) %> nav-item">
          <%= link_to courses_path, class: 'nav-link' do %>
            <div class="fa fa-book"></div>
            Courses
          <% end %>
        </li>
        <li class="<%= 'active font-weight-bold' if current_page?(new_course_path) %> nav-item">
          <%= link_to new_course_path, class: 'nav-link' do %>
            <div class="fa fa-plus"></div>
            New Course
          <% end %>
        </li>
        <li class="<%= 'active font-weight-bold' if current_page?(users_path) %> nav-item">
          <%= link_to users_path, class: 'nav-link' do %>
            <div class="fa fa-users"></div>
            Users
          <% end %>
        </li>
      </ul>
      <div class="form-inline my-2 my-lg-0">
        <%= form_tag(courses_path, :method => :get) do %>
          <div class="input-group">
            <%= text_field_tag :title, params[:title], autocomplete: 'off', placeholder: "Search", class: 'form-control-sm' %>
            <span class="input-group-append">
              <button class="btn btn-primary btn-sm" type="submit">
                <span aria-hidden="true" class="fa fa-search"></span>
              </button>
            </span>
          </div>
        <% end %>
      </div>
      <ul class="navbar-nav mr-right">
        <li class="<%= 'active font-weight-bold' if current_page?(root_path) %> nav-item">
          <%= link_to root_path, class: 'nav-link' do %>
            <div class="fa fa-home"></div>
            Another link
          <% end %>
        </li>
        <li class="nav-item dropdown">
          <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="navbarDropdown" role="button">
            <b>
              <i class="fas fa-user-circle"></i>
            </b>
          </a>
          <div aria-labelledby="navbarDropdown" class="dropdown-menu dropdown-menu-right">
            <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
              <i class="fas fa-users-cog"></i>
              Account
            <% end %>
            <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
              <i class="fa fa-sign-out-alt"></i>
              Sign out
            <% end %>
          </div>
        </li>
      </ul>
    <% else %>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Log In', new_user_session_path, class: 'nav-link' %>
        </li>
      </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %> alert-dismissible fade show" role="alert">
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
        <button aria-hidden="true" class="close" data-dismiss="alert" type="button">
          <span aria-hidden="true">&times;</span>
        </button>
      <% end %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubygemsCm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
      <main role="main">
        <div class="container mt-5">
        <%= render 'layouts/messages' %>
          <%= yield %>
        </div>
      </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/users/_user.html.erb
<div class="card">
  <div class="card-header">
    <div class="fa fa-user"></div>
    <%= user.email %>
  </div>
  <div class="card-footer">
    Signed up
    <%= time_ago_in_words(user.created_at) %>
    ago
  </div>
  <div class="card-footer">
    <div class="row small">
      <span class="font-weight-bold"> <%= 'sign_in_count'.humanize %></span>:
      <%= user.sign_in_count %>
    </div>
    <div class="row small">
      <span class="font-weight-bold"> <%= 'current_sign_in_at'.humanize %></span>:
      <%= user.current_sign_in_at %>
    </div>
    <div class="row small">
      <span class="font-weight-bold"> <%= 'last_sign_in_at'.humanize %></span>:
      <%= user.last_sign_in_at %>
    </div>
    <div class="row small">
      <span class="font-weight-bold"> <%= 'current_sign_in_ip'.humanize %></span>:
      <%= user.current_sign_in_ip %>
    </div>
    <div class="row small">
      <span class="font-weight-bold"> <%= 'last_sign_in_ip'.humanize %></span>:
      <%= user.last_sign_in_ip %>
    </div>
  </div>
  <div class="card-footer">
    Confirmed email?
    <% if user.confirmed_at.present? %>
      <div class="badge badge-success">Yes</div>
    <% else %>
      <div class="badge badge-danger">No</div>
    <% end %>
  </div>

</div>

app/views/users/index.html.erb
<div class="card-columns">
  <% @users.each do |user| %>
    <%= render 'users/user', user: user  %>
  <% end %>
</div>